kubernetes_project_id = "kubernetes-dev-94b9"
project_id            = "komreg-dev-8b16"
external_dns_hostname = "komreg-backend.dev.skip.statkart.no"
image                 = "ghcr.io/kartverket/komreg-backend:latest"
deploy_env            = "dev"