kubernetes_project_id = "kubernetes-dev-94b9"
project_id            = "komreg-dev-8b16"
container_registry    = "ghcr.io"
external_dns_hostname = "komreg-parameter-backend.dev.skip.statkart.no"
image                 = "ghcr.io/kartverket/komreg-parameter-backend:latest"
deploy_env            = "dev"