kubernetes_project_id = "kubernetes-prod-e4a2"
project_id            = "komreg-prod-6277"
external_dns_hostname = "komreg-backend.prod.skip.statkart.no"
image                 = "ghcr.io/kartverket/komreg-backend:latest"
deploy_env            = "prod"