kubernetes_project_id = "kubernetes-dev-94b9"
project_id            = "komreg-test-a245"
external_dns_hostname = "komreg-backend.test.skip.statkart.no"
image                 = "ghcr.io/kartverket/komreg-backend:latest"
deploy_env            = "test"