# Basic dependabot.yml file configuration for gradle package manager
version: 2
registries:
  maven-matrikkel:
    type: maven-repository
    url: https://maven.pkg.github.com/kartverket/matrikkel
    username: ${{ secrets.GH_USERNAME }}
    password: ${{ secrets.GH_PACKAGES_PAT }}

updates:
  # Enable version updates for gradle
  - package-ecosystem: gradle
    # Look for build.gradle files from the `root` directory
    directory: "/"
    # Check for updates every day (weekdays)
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    registries:
      - maven-matrikkel

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: daily
