# nonk8s
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "komreg-backend"
  tags:
  - "internal"
  - "private"
spec:
  type: "service"
  lifecycle: "production"
  owner: "smia"
  system: "komreg"
  providesApis:
  - "komreg-backend-api"
---
apiVersion: "backstage.io/v1alpha1"
kind: "API"
metadata:
  name: "komreg-backend-api"
  tags:
  - "internal"
spec:
  type: "openapi"
  lifecycle: "production"
  owner: "smia"
  definition: |
    openapi: "3.0.0"
    info:
        title: komreg-backend API
    paths:
