ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ no.kartverket.komreg.ApplicationKt.module ]
    }
}

database {
    url = "jdbc:h2:file:./h2database/localtransformationdb"
    driver = "org.h2.Driver"
    username = "sa"
    password = ""
}