ktor {
    deployment {
        port = 8080
        port = ${?PORT}
        responseWriteTimeoutSeconds = -1
    }
    application {
        modules = [ no.kartverket.komreg.ApplicationKt.module ]
    }
}
