integration.matrikkel.backing {
    jdbcUrl = "jdbc:oracle:thin:@//localhost:1521/devmatr1"
    jdbcUrl = ${?DB_MATRIKKEL_JDBC_URL}
    user = "MATRIKKEL_DEV"
    user = ${?DB_MATRIKKEL_BACKING_USERNAME}
    password = "MATRIKKEL_DEV"
    password = ${?DB_MATRIKKEL_BACKING_PASSWORD}
    schema = "MATRIKKEL_DEV"
}

integration.matrikkel.mottaker1 {
    jdbcUrl = "jdbc:oracle:thin:@//localhost:1521/devmatr1"
    jdbcUrl = ${?DB_MATRIKKEL_JDBC_URL}
    user = "MATRIKKEL_DEV"
    user = ${?DB_MATRIKKEL_MOTTAKER1_USERNAME}
    password = "MATRIKKEL_DEV"
    password = ${?DB_MATRIKKEL_MOTTAKER1_PASSWORD}
    schema = "MATRIKKEL_DEV"
}

integration.matrikkel.mottaker2 {
    jdbcUrl = "jdbc:oracle:thin:@//localhost:1521/devmatr1"
    jdbcUrl = ${?DB_MATRIKKEL_JDBC_URL}
    user = "MATRIKKEL_DEV"
    user = ${?DB_MATRIKKEL_MOTTAKER2_USERNAME}
    password = "MATRIKKEL_DEV"
    password = ${?DB_MATRIKKEL_MOTTAKER2_PASSWORD}
    schema = "MATRIKKEL_DEV"
}

integration.matrikkel.system {
    jdbcUrl = "jdbc:oracle:thin:@//localhost:1521/devmatr1"
    jdbcUrl = ${?DB_MATRIKKEL_JDBC_URL}
    user = "SYSTEM"
    user = ${?DB_MATRIKKEL_SYSTEM_USERNAME}
    password = "password"
    password = ${?DB_MATRIKKEL_SYSTEM_PASSWORD}

}

feature {
    disable_sink = false
    disable_sink = ${?TOGGLE_SINK_OFF}
}
