POST http://localhost:8080/run HTTP/1.1
Content-Type: application/json

{
  "id": "fylkesdeling-2024",
  "navn": "Fylkesdeling 2024",
  "dato": "2024-01-01",
  "endringer": [
    {
      "id": "fylkesdeling",
      "navn": "Den store Viken-delingen anno 2024",
      "type": "Fylkesdeling",
      "gammeltFylke": {
        "navn": "Viken",
        "fylkesnummer": "30",
        "kommuner": []
      },
      "nyeFylker": [
        {
          "navn": "Østfold",
          "fylkesnummer": "31",
          "kommuner": [
            {
              "navn": "Fredrikstad",
              "kommunenummer": "3004",
              "nyttKommunenummer": "3107"
            },
            {
              "navn": "Hvaler",
              "kommunenummer": "3011",
              "nyttKommunenummer": "3110"
            }
          ]
        },
        {
          "navn": "Akershus",
          "fylkesnummer": "32",
          "kommuner": [
            {
              "navn": "Asker",
              "kommunenummer": "3025",
              "nyttKommunenummer": "3203"
            },
            {
              "navn": "Gjerdrum",
              "kommunenummer": "3032",
              "nyttKommunenummer": "3230"
            }
          ]
        },
        {
          "navn": "Buskerud",
          "fylkesnummer": "33",
          "kommuner": [
            {
              "navn": "Ringerike",
              "kommunenummer": "3007",
              "nyttKommunenummer": "3305"
            },
            {
              "navn": "Hemsedal",
              "kommunenummer": "3042",
              "nyttKommunenummer": "3326"
            }
          ]
        }
      ]
    },
    {
      "id": "forsøkpåmatrikkelenhet",
      "navn": "Test av matrikkelenhetendring",
      "type": "Fylkesdeling",
      "gammeltFylke": {
        "navn": "Akershus",
        "fylkesnummer": "2",
        "kommuner": []
      },
      "nyeFylker": [
        {
          "navn": "Akershus",
          "fylkesnummer": "2",
          "kommuner": [
            {
              "navn": "Hølen",
              "kommunenummer": "0204",
              "nyttKommunenummer": "0205"
            }
          ]
        }
      ]
    }
  ]
}
