integration.matrikkel.kilde {
    jdbcUrl = "jdbc:oracle:thin:@//localhost:1521/devmatr1"
    jdbcUrl = ${?DB_MATRIKKEL_JDBC_URL}
    user = "MATRIKKEL_DEV"
    user = ${?DB_MATRIKKEL_KILDE_USERNAME}
    password = "MATRIKKEL_DEV"
    password = ${?DB_MATRIKKEL_KILDE_PASSWORD}
    schema = "MATRIKKEL_DEV"
}

integration.matrikkel.mottaker {
    jdbcUrl = "jdbc:oracle:thin:@//localhost:1521/devmatr1"
    jdbcUrl = ${?DB_MATRIKKEL_JDBC_URL}
    user = "MATRIKKEL_DEV"
    user = ${?DB_MATRIKKEL_MOTTAKER_USERNAME}
    password = "MATRIKKEL_DEV"
    password = ${?DB_MATRIKKEL_MOTTAKER_PASSWORD}
    schema = "MATRIKKEL_DEV"
}

feature {
    disable_sink = false
    disable_sink = ${?TOGGLE_SINK_OFF}
}

integration.komreg.db {
    jdbcUrl = ${?DB_KOMREG_JDBC_URL}
    user = ${?DB_KOMREG_USERNAME}
    password = ${?DB_KOMREG_PASSWORD}
}
