integration.matrikkel {
    jdbcUrl = "jdbc:oracle:thin:@//localhost:1521/devmatr1"
    user = "MATRIKKEL_DEV"
    password = "MATRIKKEL_DEV"
    schema = "MATRIKKEL_DEV"
}

integration.matrikkel {
    jdbcUrl = "jdbc:oracle:thin:@//localhost:1521/devmatr1"
    user = "MATRIKKEL_DEV"
    password = "MATRIKKEL_DEV"
    schema = "MATRIKKEL_DEV"
}
