komreg {
    db_matrikkel_jdbc_url = "sm://komreg-dev-8b16/db_matrikkel_jdbc_url/1"
    db_matrikkel_username = "sm://komreg-dev-8b16/db_matrikkel_username/1"
    db_matrikkel_password = "sm://komreg-dev-8b16/db_matrikkel_password/1"
}