integration.matrikkel.kilde {
    jdbcUrl = "sm://komreg-dev-8b16/db_matrikkel_jdbc_url/2"
    user = "sm://komreg-dev-8b16/db_matrikkel_kilde_username/1"
    password = "sm://komreg-dev-8b16/db_matrikkel_kilde_password/1"
    schema = "ALFA1_KILDE"
}
integration.matrikkel.mottaker {
    jdbcUrl = "sm://komreg-dev-8b16/db_matrikkel_jdbc_url/2"
    user = "sm://komreg-dev-8b16/db_matrikkel_mottaker_username/1"
    password = "sm://komreg-dev-8b16/db_matrikkel_mottaker_password/1"
    schema = "ALFA1_MOTTAKER"
}
