integration.matrikkel.kilde {
    jdbcUrl = "sm://komreg-dev-8b16/db_matrikkel_jdbc_url/2"
    user = "sm://komreg-dev-8b16/db_matrikkel_username/2"
    password = "sm://komreg-dev-8b16/db_matrikkel_password/2"
    schema = "ALFA1_KILDE"
}
integration.matrikkel.mottaker {
    jdbcUrl = "sm://komreg-dev-8b16/db_matrikkel_jdbc_url/2"
    user = "sm://komreg-dev-8b16/db_matrikkel_username/2"
    password = "sm://komreg-dev-8b16/db_matrikkel_password/2"
    schema = "ALFA1_MOTTAKER"
}