name: Build and Publish Matrikkel Komreg
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to publish'
        required: true

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-matrikkel:
    name: Bygg matrikkel
    runs-on: ubuntu-latest
    steps:
      - name: Sett opp Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:github-runner
          version: latest
          ping: 'nexus.statkart.no'
      - uses: actions/checkout@v6
        with:
          path: komreg-backend
      - uses: octo-sts/action@f603d3be9d8dd9871a265776e625a27b00effe05 # v1.1.1
        id: octo-sts
        with:
          scope: kartverket/matrikkel
          identity: komreg-checkout-code
      - uses: actions/checkout@v6
        with:
          repository: kartverket/matrikkel
          ref: refs/tags/${{ github.event.inputs.tag }}
          path: matrikkel
          token: ${{ steps.octo-sts.outputs.token }}
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17
      - uses: gradle/actions/setup-gradle@v5
      - name: Build with Gradle
        working-directory: matrikkel
        run: ./gradlew --console=plain --configure-on-demand --init-script ../komreg-backend/matrikkel-komreg-publish.init.gradle -Pmatrikkel_artifact_versjon=${{ github.event.inputs.tag }} :komreg:publishKomregMatrikkelPublicationToKomregBackendRepository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
