name: CD - Build and deploy to dev
on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  registry: ghcr.io
  image_name: ${{ github.repository }}

jobs:
  build:
    name: Docker build and push
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    outputs:
      image_url: ${{ steps.setOutput.outputs.image_url }}
      digest: ${{ steps.setOutput.outputs.digest }}
      version: ${{ steps.setOutput.outputs.version }}
    steps:
      - name: Checkout project sources
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0

      - name: Build with Gradle
        run: ./gradlew build integrationTest --info
        env:
          GH_PACKAGES_PAT: ${{ secrets.GH_PACKAGES_PAT }}

      - name: Login to Github Container Registry
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b #v6.2.0
        with:
          github_token: ${{ github.token }}

      - name: Build docker and push
        id: build
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a #v7.3.0
        with:
          context: server/build/docker
          push: true
          tags: ${{ env.registry }}/${{ github.repository }}:${{ steps.tag_version.outputs.new_tag }},${{ env.registry }}/${{ github.repository }}:latest

      - name: Set output with build values
        id: setOutput
        run: |
          echo "version=${{ steps.tag_version.outputs.new_tag }}" >> $GITHUB_OUTPUT
          echo "digest=${{ steps.build.outputs.digest }}" >> $GITHUB_OUTPUT
          echo "image_url=${{ env.registry }}/${{ env.image_name }}:${{ steps.tag_version.outputs.new_tag }}" >> $GITHUB_OUTPUT

  pharos:
    name: Run Pharos with Required Permissions
    needs: build
    permissions:
      actions: read
      packages: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - name: "Run Pharos"
        uses: kartverket/pharos@e5a5cf71dd41384d6d62c7d9b387851c0457e81b # v0.6.4
        with:
          image_url: ${{ needs.build.outputs.image_url}}
          disable_severity_check: true

#  should-deploy-argo:
#    uses: ./.github/workflows/check-is-komreg-dev-running.yml
#    secrets: inherit

  deploy-argo:
#    if: ${{ needs.should-deploy-argo.outputs.isRunning == 'false' }}
#    needs: [ build, should-deploy-argo ]
      needs: [ build ]
      permissions:
        id-token: write
        contents: read
      uses: kartverket/smia-workflows/.github/workflows/deploy-app.yml@main
      with:
        application: komreg-backend
        version: ${{ needs.build.outputs.version }}
        digest: ${{ needs.build.outputs.digest }}
        environment: dev
        identity: komreg
        namespace: komreg-main
