name: CD - Build and deploy to dev
on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  registry: ghcr.io
  image_name: ${{ github.repository }}
  argo_version_file: backend-version

jobs:
  build:
    name: Docker build and push
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    outputs:
      image_url: ${{ steps.setOutput.outputs.image_url }}
      version: ${{ steps.tag_version.outputs.new_tag }}
    steps:
      - name: Checkout project sources
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0

      - name: Build with Gradle
        run: ./gradlew build integrationTest --info
        env:
          GH_PACKAGES_PAT: ${{ secrets.SHARED_PACKAGES_READ_TOKEN }}

      - name: Login to Github Container Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b #v6.2.0
        with:
          github_token: ${{ github.token }}

      - name: Build docker and push
        id: build
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf #v7.2.0
        with:
          context: server/build/docker
          push: true
          tags: ${{ env.registry }}/${{ github.repository }}:${{ steps.tag_version.outputs.new_tag }},${{ env.registry }}/${{ github.repository }}:latest

      - name: Set output with build values
        id: setOutput
        run: |
          echo "image_url=${{ env.registry }}/${{ github.repository }}@${{ steps.build.outputs.digest }}" >> $GITHUB_OUTPUT

  pharos:
    name: Run Pharos with Required Permissions
    needs: build
    permissions:
      actions: read
      packages: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - name: "Run Pharos"
        uses: kartverket/pharos@599d3fe4af8bae19fbfda831662e90ee1c406ec2 # v0.6.3
        with:
          image_url: ${{ needs.build.outputs.image_url}}
          disable_severity_check: true

  deploy-argo:
    needs: [ build ]
    permissions:
      id-token: write
      contents: read
    uses: kartverket/smia-apps/.github/workflows/release-app-octo-sts.yml@main
    with:
      application: komreg-backend
      version: ${{ needs.build.outputs.version }}
      deploy_dev: true
      deploy_prod: false
      identity: komreg
      namespace: komreg-main
