name: CI - PR Validation and Test

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and run Integration Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout project sources
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and run Integration Test with Gradle
        run: ./gradlew build integrationTest
        env:
          GH_PACKAGES_PAT: ${{ secrets.GH_PACKAGES_PAT}}
