name: CI - PR Validation and Test

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and run Integration Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout project sources
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and run Integration Test with Gradle
        run: ./gradlew build integrationTest
        env:
          GH_PACKAGES_PAT: ${{ secrets.GH_PACKAGES_PAT}}
