name: CI - PR Validation and Test

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and run Integration Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout project sources
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and run Integration Test with Gradle
        run: ./gradlew build integrationTest
        env:
          GH_PACKAGES_PAT: ${{ secrets.GH_PACKAGES_PAT}}
