name: Build and Deploy Branch
on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:
    inputs:
      deploy_dev:
        description: 'Should deploy build to dev environment'
        required: false
        type: boolean
        default: false

permissions:
  id-token: write
  contents: "read"

env:
  registry: ghcr.io
  image_name: ${{ github.repository }}

jobs:
  build:
    name: Docker build and push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image_url: ${{ steps.setOutput.outputs.image_url }}
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5.1
      - name: Run build with Gradle Wrapper
        run: gradle build

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ github.token }}

      - name: Build docker and push
        id: build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.registry }}/${{ github.repository }}:${{ steps.tag_version.outputs.new_tag }},${{ env.registry }}/${{ github.repository }}:latest

      - name: Set output with build values
        id: setOutput
        run: |
          echo "image_url=${{ env.registry }}/${{ github.repository }}@${{ steps.build.outputs.digest }}" >> $GITHUB_OUTPUT

  security-scans:
    needs: build
    name: Security Scans
    permissions:
      contents: read
      packages: write
      id-token: write
      actions: read
      security-events: write
    uses: kartverket/github-workflows/.github/workflows/run-security-scans.yml@v4.0.0
    with:
      auth_project_number: 172982192640
      service_account: komreg-deploy@komreg-dev-8b16.iam.gserviceaccount.com
      image_url: ${{ needs.build.outputs.image_url}}

  deploy-dev:
    name: Deploy to dev
    needs: build
    uses: kartverket/github-workflows/.github/workflows/run-terraform.yml@v4.0.0
    permissions:
      id-token: write
      pull-requests: write
      contents: read
      packages: write
    with:
      runner: ubuntu-latest
      environment: dev
      kubernetes_cluster: atkv1-dev
      terraform_option_1: -var-file=variables/dev.tfvars
      terraform_option_2: -var=image=${{ needs.build.outputs.image_url }}
      terraform_init_option_1: -backend-config=backend/dev.gcs.tfbackend
      working_directory: terraform
      auth_project_number: 172982192640
      service_account: komreg-deploy@komreg-dev-8b16.iam.gserviceaccount.com
      project_id: kubernetes-dev-94b9
      deploy_on: ${{ github.ref }}
