name: Deploy
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy'
        required: true
      deploy_prod:
        description: 'Deploy to production'
        type: boolean
        required: true
        default: false
      deploy_dev:
        description: 'Deploy to development'
        type: boolean
        required: true
        default: true

permissions:
  id-token: write

jobs:
  deploy-argo:
    uses: kartverket/smia-apps/.github/workflows/release-app-octo-sts.yml@main
    with:
      application: komreg-backend
      version: ${{ github.event.inputs.version }}
      deploy_dev: ${{ github.event.inputs.deploy_dev && 'true' || 'false' }}
      deploy_prod: ${{ github.event.inputs.deploy_prod && 'true' || 'false' }}
      identity: komreg
      namespace: komreg-main
