name: Publish core-api to GH-packages

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Ønsket versjonsnummer på pakke'
        required: true

jobs:
  calculate-version:
    name: Calculate version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version-string.outputs.version }}

    steps:
      -   name: Generate version string
          id: version-string
          shell: bash
          run: |
            version="${{ inputs.version }}-$(date -u '+%Y.%m.%d-%H.%M')-$(echo "${GITHUB_SHA}" | cut -c1-7)"
            echo "version=${version}" >> "$GITHUB_OUTPUT"

  publish:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    needs:
      - calculate-version

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up JDK 17
        uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # v5.5.0
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Publish to GitHub Packages
        run: ./gradlew publish -p core-api -Pmatrikkel_artifact_versjon=${{ needs.calculate-version.outputs.version }}
        env:
          GH_PACKAGES_PAT: ${{ secrets.GH_PACKAGES_PAT}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
